In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, OneHotEncoder, KBinsDiscretizer, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

Create a few ColumnTransformers and train them on the Titanic data. Here are a few ideas to work on:

impute the missing values in the Age column

one-hot-encode the Embarked column

bin the imputed Age column into 3 bins (young, middle-aged, old)

scale the Fare column

In [61]:
df = pd.read_csv('train.csv', index_col='PassengerId')
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [62]:
df.isna().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [63]:
df.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [64]:
X = df[['Pclass','Sex','Age','Fare','Embarked']]
y = df['Survived']

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25,random_state= 42)

In [66]:
#X_train_trans.shape, X_test_trans.shape, y_train_trans.shape, y_test_trans.shape

In [67]:
pipeline_sex = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse=False, drop="if_binary")),
])

In [68]:
pipeline_age = Pipeline([
    ("imputer", SimpleImputer(strategy='most_frequent')),
    ("binning", KBinsDiscretizer(n_bins=10, encode='onehot-dense', strategy='uniform'))
])

In [69]:
pipeline_embarked = Pipeline([
    ("imputer", SimpleImputer(strategy='most_frequent')),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse=False))
])

In [70]:
pipeline_fare = Pipeline([
    ("binning", KBinsDiscretizer(n_bins=4, encode='onehot-dense', strategy='uniform'))
])

In [71]:
pipeline_class = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse=False))
])

In [72]:
transformer = ColumnTransformer(
    [
        ("sex", pipeline_sex, ['Sex']),
        ('fare', pipeline_fare, ['Fare']),
        ("age", pipeline_age, ['Age']),
        ("embarked", pipeline_embarked, ['Embarked']),
        ("class", pipeline_class, ['Pclass'])

    ]
)

In [73]:
train_FE = transformer.fit_transform(X_train)
#train_FE

In [74]:
test_FE = transformer.transform(X_test)
#valid_transform

In [75]:
clf = LogisticRegression()

In [76]:
clf.fit(train_FE, y_train)

LogisticRegression()

In [77]:
clf.predict(test_FE)

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0])

In [78]:
clf.predict_proba(test_FE)

array([[0.87389855, 0.12610145],
       [0.69399798, 0.30600202],
       [0.93300529, 0.06699471],
       [0.05748302, 0.94251698],
       [0.31972309, 0.68027691],
       [0.09029306, 0.90970694],
       [0.38950391, 0.61049609],
       [0.9228362 , 0.0771638 ],
       [0.35396084, 0.64603916],
       [0.15240105, 0.84759895],
       [0.65858614, 0.34141386],
       [0.93782812, 0.06217188],
       [0.52376974, 0.47623026],
       [0.79277064, 0.20722936],
       [0.77683086, 0.22316914],
       [0.13375386, 0.86624614],
       [0.71148786, 0.28851214],
       [0.38950391, 0.61049609],
       [0.69399798, 0.30600202],
       [0.71148786, 0.28851214],
       [0.93300529, 0.06699471],
       [0.65858614, 0.34141386],
       [0.52376974, 0.47623026],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.9228362 , 0.0771638 ],
       [0.48977152, 0.51022848],
       [0.69399798, 0.30600202],
       [0.72358849, 0.27641151],
       [0.37777121, 0.62222879],
       [0.93300529, 0.06699471],
       [0.52376974, 0.47623026],
       [0.53116825, 0.46883175],
       [0.52376974, 0.47623026],
       [0.93300529, 0.06699471],
       [0.79277064, 0.20722936],
       [0.55689861, 0.44310139],
       [0.38950391, 0.61049609],
       [0.0470666 , 0.9529334 ],
       [0.93300529, 0.06699471],
       [0.80424612, 0.19575388],
       [0.88489531, 0.11510469],
       [0.93300529, 0.06699471],
       [0.88985378, 0.11014622],
       [0.37217389, 0.62782611],
       [0.9228362 , 0.0771638 ],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.56528462, 0.43471538],
       [0.0932795 , 0.9067205 ],
       [0.15963546, 0.84036454],
       [0.9218709 , 0.0781291 ],
       [0.66161031, 0.33838969],
       [0.9240527 , 0.0759473 ],
       [0.15240105, 0.84759895],
       [0.69399798, 0.30600202],
       [0.08954082, 0.91045918],
       [0.21562376, 0.78437624],
       [0.38950391, 0.61049609],
       [0.93300529, 0.06699471],
       [0.21791215, 0.78208785],
       [0.15190091, 0.84809909],
       [0.69482071, 0.30517929],
       [0.88985378, 0.11014622],
       [0.27134757, 0.72865243],
       [0.80424612, 0.19575388],
       [0.88489531, 0.11510469],
       [0.87389855, 0.12610145],
       [0.08636391, 0.91363609],
       [0.15190091, 0.84809909],
       [0.08204418, 0.91795582],
       [0.38477366, 0.61522634],
       [0.07046515, 0.92953485],
       [0.93300529, 0.06699471],
       [0.9218709 , 0.0781291 ],
       [0.26046217, 0.73953783],
       [0.08212554, 0.91787446],
       [0.21562376, 0.78437624],
       [0.54364303, 0.45635697],
       [0.9228362 , 0.0771638 ],
       [0.15190091, 0.84809909],
       [0.07310401, 0.92689599],
       [0.88985378, 0.11014622],
       [0.54482532, 0.45517468],
       [0.63048914, 0.36951086],
       [0.0470666 , 0.9529334 ],
       [0.0470666 , 0.9529334 ],
       [0.65858614, 0.34141386],
       [0.93300529, 0.06699471],
       [0.9228362 , 0.0771638 ],
       [0.4857226 , 0.5142774 ],
       [0.72323339, 0.27676661],
       [0.88985378, 0.11014622],
       [0.93300529, 0.06699471],
       [0.88489531, 0.11510469],
       [0.71148786, 0.28851214],
       [0.93782812, 0.06217188],
       [0.21562376, 0.78437624],
       [0.88489531, 0.11510469],
       [0.72323339, 0.27676661],
       [0.9218709 , 0.0781291 ],
       [0.08212554, 0.91787446],
       [0.9218709 , 0.0781291 ],
       [0.88489531, 0.11510469],
       [0.88489531, 0.11510469],
       [0.21562376, 0.78437624],
       [0.71148786, 0.28851214],
       [0.88489531, 0.11510469],
       [0.48977152, 0.51022848],
       [0.15240105, 0.84759895],
       [0.93300529, 0.06699471],
       [0.08212554, 0.91787446],
       [0.65858614, 0.34141386],
       [0.70315399, 0.29684601],
       [0.93300529, 0.06699471],
       [0.63048914, 0.36951086],
       [0.63399014, 0.36600986],
       [0.24497415, 0.75502585],
       [0.54364303, 0.45635697],
       [0.80424612, 0.19575388],
       [0.0470666 , 0.9529334 ],
       [0.17106629, 0.82893371],
       [0.43575267, 0.56424733],
       [0.88489531, 0.11510469],
       [0.48977152, 0.51022848],
       [0.15963546, 0.84036454],
       [0.53116825, 0.46883175],
       [0.35371048, 0.64628952],
       [0.93300529, 0.06699471],
       [0.38950391, 0.61049609],
       [0.87389855, 0.12610145],
       [0.80424612, 0.19575388],
       [0.1713181 , 0.8286819 ],
       [0.54482532, 0.45517468],
       [0.31972309, 0.68027691],
       [0.08212554, 0.91787446],
       [0.88489531, 0.11510469],
       [0.93782812, 0.06217188],
       [0.52376974, 0.47623026],
       [0.93300529, 0.06699471],
       [0.26004542, 0.73995458],
       [0.69399798, 0.30600202],
       [0.77683086, 0.22316914],
       [0.35088475, 0.64911525],
       [0.21562376, 0.78437624],
       [0.69399798, 0.30600202],
       [0.86086921, 0.13913079],
       [0.08516107, 0.91483893],
       [0.93782812, 0.06217188],
       [0.87389855, 0.12610145],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.38950391, 0.61049609],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.38950391, 0.61049609],
       [0.21562376, 0.78437624],
       [0.26046217, 0.73953783],
       [0.87389855, 0.12610145],
       [0.69482071, 0.30517929],
       [0.77683086, 0.22316914],
       [0.08212554, 0.91787446],
       [0.88985378, 0.11014622],
       [0.63048914, 0.36951086],
       [0.80424612, 0.19575388],
       [0.15240105, 0.84759895],
       [0.93300529, 0.06699471],
       [0.9218709 , 0.0781291 ],
       [0.53116825, 0.46883175],
       [0.24497415, 0.75502585],
       [0.65858614, 0.34141386],
       [0.31972309, 0.68027691],
       [0.93300529, 0.06699471],
       [0.87389855, 0.12610145],
       [0.48235639, 0.51764361],
       [0.24497415, 0.75502585],
       [0.1713181 , 0.8286819 ],
       [0.71148786, 0.28851214],
       [0.80424612, 0.19575388],
       [0.88489531, 0.11510469],
       [0.88489531, 0.11510469],
       [0.1713181 , 0.8286819 ],
       [0.54101832, 0.45898168],
       [0.71148786, 0.28851214],
       [0.53020263, 0.46979737],
       [0.93300529, 0.06699471],
       [0.69482071, 0.30517929],
       [0.26004542, 0.73995458],
       [0.9218709 , 0.0781291 ],
       [0.77683086, 0.22316914],
       [0.93300529, 0.06699471],
       [0.88489531, 0.11510469],
       [0.25527946, 0.74472054],
       [0.13219987, 0.86780013],
       [0.07310401, 0.92689599],
       [0.77683086, 0.22316914],
       [0.15240105, 0.84759895],
       [0.4857226 , 0.5142774 ],
       [0.94112171, 0.05887829],
       [0.37777121, 0.62222879],
       [0.05748302, 0.94251698],
       [0.55797647, 0.44202353],
       [0.87389855, 0.12610145],
       [0.35371048, 0.64628952],
       [0.88489531, 0.11510469],
       [0.65858614, 0.34141386],
       [0.87389855, 0.12610145],
       [0.93635931, 0.06364069],
       [0.39419153, 0.60580847],
       [0.88489531, 0.11510469],
       [0.08119687, 0.91880313],
       [0.88985378, 0.11014622],
       [0.52376974, 0.47623026],
       [0.72358849, 0.27641151],
       [0.15190091, 0.84809909],
       [0.54482532, 0.45517468],
       [0.15190091, 0.84809909],
       [0.93300529, 0.06699471],
       [0.93300529, 0.06699471],
       [0.24497415, 0.75502585],
       [0.93300529, 0.06699471]])

In [79]:
clf.score(train_FE, y_train)

0.8203592814371258

In [80]:
clf.score(test_FE, y_test)

0.8071748878923767

clf.score(X_train_FE, y_train_trans) 

0.8203592814371258

clf.score(X_test_FE, y_test_trans)

0.8071748878923767